//
//  MotorcycleEntity+CoreDataProperties.swift
//  
//
//  Created by Sanny on 2025/12/4.
//
//
/* autogenerated
import Foundation
import CoreData


extension MotorcycleEntity {

    @nonobjc public class func fetchRequest() -> NSFetchRequest<MotorcycleEntity> {
        return NSFetchRequest<MotorcycleEntity>(entityName: "MotorcycleEntity")
    }

    @NSManaged public var color: UIColor?
    @NSManaged public var image: UIImage?
    @NSManaged public var name: String?

}
 */
