//
//  MotorcycleEntity+CoreDataClass.swift
//  
//
//  Created by Sanny on 2025/12/4.
//
//
/* autogenerated
import Foundation
import CoreData

@objc(MotorcycleEntity)
public class MotorcycleEntity: NSManagedObject {

}
 */

import CoreData
import SwiftUI
import UIKit

class MotorcycleEntity: NSManagedObject, Identifiable {
    @NSManaged public var color: UIColor?
    @NSManaged public var image: UIImage?
    @NSManaged public var name: String?
    @NSManaged public var specs: MotorcycleTechnicalSpecification?
    
    @nonobjc public class func fetchRequest() -> NSFetchRequest<MotorcycleEntity> {
        return NSFetchRequest<MotorcycleEntity>(entityName: "MotorcycleEntity")
    }
}

extension MotorcycleEntity {
    
    var viewName: String {
        name ?? "N/A"
    }
    
    var viewColor: Color {
        if let color {
            return Color(color)
        }
        return Color.clear
    }
    
    var viewImage: Image {
        if let image {
            return Image(uiImage: image)
        }
        return Image(systemName: "photo")
    }
    
    var viewHorsepower: Int {
        return specs?.horsepower ?? 0
    }
    
    var viewWeight: Measurement<UnitMass> {
        let kilograms = specs?.weight ?? 0.0
        return Measurement(value: kilograms, unit: UnitMass.kilograms)
    }
    
    var viewEngine: String {
        return specs?.engine ?? "N/A"
    }
}
